[build]
rustflags = [
    "-Wmissing_docs",
    "-Wclippy::dbg_macro ",
    "-Dunsafe_op_in_unsafe_fn",
    "-Drust_2018_idioms",
    "-Dnon_ascii_idents",
    "-Drustdoc::missing_crate_level_docs",
    "-Dclippy::correctness",
    "-Dclippy::style",
    "-Dclippy::suspicious",
    "-Dclippy::complexity",
    "-Dclippy::perf",
    "-Dclippy::let_unit_value",
    "-Dclippy::mut_mut",
    "-Dclippy::needless_bitwise_bool",
    "-Dclippy::needless_continue",
    "-Zbinary_dep_depinfo=y",
    "-Zcrate-attr=no_std",
    "-Zcrate-attr=feature(allocator_api,bench_black_box,concat_idents,generic_associated_types)",
    "-Zmacro-backtrace",
    "-L", "../../rust/",
    "--emit=dep-info,obj",
    "-Cpanic=abort",
    "-Cembed-bitcode=n",
    "-Clto=n",
    "-Cforce-unwind-tables=n",
    "-Ccodegen-units=1",
    "-Csymbol-mangling-version=v0",
    "-Crelocation-model=static",
    "-Ctarget-feature=-mmx,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2",
    "-Ctarget-feature=-3dnow,-3dnowa,-avx,-avx2,+soft-float",
    "-Cno-redzone=y",
    "-Ccode-model=kernel",
    "-Ctarget-feature=+retpoline-external-thunk",
    "-Cdebug-assertions=n",
    "-Coverflow-checks=y",
    "-Copt-level=2",
    "-Cdebuginfo=2",
    "--cfg",
    "MODULE",
    "@../../include/generated/rustc_cfg",
]

target = "../../rust/target.json"